development:
  adapter: postgresql
  database: my_database_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_database_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_database_production
  pool: 5
  timeout: 5000